# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#1_about"
  weight = 10

[[main]]
  name = "Research"
  url = "#2_research"
  weight = 20

[[main]]
  name = "Publications"
  url = "#3_publications"
  weight = 30

[[main]]
  name = "Teaching"
  url = "#4_teaching"
  weight = 40

[[main]]
  name = "CV"
  url = "files/MGR_CV_full.pdf"
  weight = 50

[[main]]
  name = "Contact"
  url = "#9_contact"
  weight = 60
